services:
  - type: web
    name: api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb://mongodb:27017/ProyectoApi

  - type: private_service
    name: mongodb
    env: docker
    plan: free
    dockerfilePath: ''  # Vacío porque usamos una imagen de DockerHub (mongo:latest)
    image: mongo:latest
